jobs:
    - amd_samples:
        source: /opt/AMDAPP/samples/opencl/cl/
        output: /tmp/demo
        recursive: true
        extension: cl
        device_type: gpu
        device_index: 0
        device_regex: Oland
        platform_regex: AMD
        platform_index: 0
        options: -Dtest=22
        verbose: 2
    - amd_samples2:
        source: /opt/AMDAPP/samples/opencl/cl/
        output: /tmp/demo2
        recursive: true
        extension: cl
        device_type: gpu
        device_index: 0
        device_regex: Oland
        platform_index: 0
        options: -Dtest=22
        verbose: 1