jobs:
    - gromacs:
        source: /home/gnieto/git/gromacs/src/gromacs
        output: /tmp/gromacs
        recursive: true
        extension: cl
        verbose: 3
        options: -D _AMD_SOURCE_ -I/home/gnieto/git/gromacs/src/gromacs/mdlib/nbnxn_ocl/ -I/home/gnieto/git/gromacs/src/gromacs/gmxlib/ocl_tools/ -I/home/gnieto/git/gromacs/src/gromacs/mdlib/ -I/home/gnieto/git/gromacs/src/gromacs/pbcutil/
        device_type: all
    - broccoli:
        source: /home/gnieto/git/BROCCOLI/code/Kernels
        output: /tmp/broccoli
        recursive: true
        extension: cpp
        verbose: 3
        device_type: all
    - johnTheRipper_office2007:
        source: /home/gnieto/git/JohnTheRipper/src/opencl/office2007_kernel.cl
        output: /tmp/john
        extension: cl
        verbose: 3
        options: -I/home/gnieto/git/JohnTheRipper/src -DUNICODE_LENGTH=104 -DHASH_LOOPS=500
        device_type: all
        tag: office_2007